### ISSUE TITLE
Antistorm sensor cause problems with other device

### ISSUE THREAD

**Issue by PrzemekSkw** [PiotrMachowski/Home-Assistant-custom-components-Antistorm#12]
Hello, I add example sensor/binary sensor to my configuration.yaml at the end. Then I noticed that some of my entities from Xiaomi Air Purifier not work. When I add that sensor on top of my file it don't work at all.
https://paste.pics/d13a1bb9fe63de929d80f931708c9b34
https://paste.pics/1d794cb4561e314b3b32888eb8b3278c
Regards.

**Comment by PiotrMachowski** [comment]
I don't think it's possible... Can you show related part of configuration.yaml file?

**Comment by PrzemekSkw** [comment]
I also noticed my nextcloud sensor are not working with antistorm.
That is my full configuration.yaml:
```
dietpi@DietPi:~$ sudo cat /mnt/Toshiba/dietpi_userdata/homeassistant/configuration.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#======================
# Text to speech
#======================
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#==================================
# Emby - media player
#==================================
media_player:
  - platform: emby
    host: 192.168.0.19
    api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    port: 8096
#==================================
# SONOFF - Smart Socket
#==================================
sonoff:
  username: xxxxxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxxx
  mode: local
  reload: always  # update device list every time HA starts

#==================================
# NEXTCLOUD
#==================================
nextcloud:
  url: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  username: xxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxxxxxxxx

#======================================
# SYSTEM-MONITOR
#======================================
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free

#======================#
#  Mi Air Purifier 3H  #
#======================#
#fan:
#  - platform: xiaomi_miio
#    name: "Mi Air Purifier 3H"
#    host: !secret mi_air_host
#    token: !secret mi_air_token
#    model: zhimi.airpurifier.mb3
input_select:
    mi_air_purifier_3h_coverage:
      name: Coverage
      options:
        - 2-4 m²
        - 5-9 m²
        - 7-12 m²
        - 12-22 m²
        - 14-24 m²
        - 14-25 m²
        - 16-27 m²
        - 17-30 m²
        - 18-32 m²
        - 19-33 m²
        - 20-34 m²
        - 22-38 m²
        - 23-40 m²
        - 26-45 m²
        - 28-49 m²
      icon: mdi:texture-box


#===========#
#  Sensors  #
#===========#
sensor:

  #======================#
  #  Mi Air Purifier 3H  #
  #======================#
  - platform: template
    sensors:
      mi_air_purifier_3h_pm2_5_severity:
        friendly_name: "PM2.5 severity level"
        value_template: >-
          {% if states('sensor.mi_air_purifier_3_3h_pm2_5') | int > 30 %}
            {{ 'critical' }}
          {% elif states('sensor.mi_air_purifier_3_3h_pm2_5') | int > 15 %}
            {{ 'polluted' }}
          {% else %}
            {{ 'clean' }}
          {% endif %}
        icon_template: "mdi:air-filter"
      mi_air_purifier_3h_use_time:
        friendly_name: "Time used"
#        value_template: "{{ state_attr('fan.mi_air_purifier_3h', 'use_time') }}"
        value_template: >
            {% macro phrase(value, name) %}
            {%- set value = value | int %}
            {%- set end = 's' if value > 1 else '' %}
            {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
            {%- endmacro %}

            {% set weeks = (state_attr('fan.mi_air_purifier_3_3h', 'use_time') | int / 604800) | int %}
            {% set days = ((state_attr('fan.mi_air_purifier_3_3h', 'use_time') | int - (weeks * 604800)) / 86400) | int %}
            {% set hours = ((state_attr('fan.mi_air_purifier_3_3h', 'use_time') | int - (weeks * 604800) - (days * 86400)) / 3600) | int %}
            {% set minutes = ((state_attr('fan.mi_air_purifier_3_3h', 'use_time') | int - (weeks * 604800) - (days * 86400) - (hours * 3600)) / 60) | int %}
            {% set seconds = (state_attr('fan.mi_air_purifier_3_3h', 'use_time') | int - (weeks * 604800) - (days * 86400) - (hours * 3600) - (minutes*60)) | int %}
            {{ [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min'), phrase(seconds, 'sec') ] | select('!=','') | list | join(', ') }}
#        unit_of_measurement: "sec"
        icon_template: "mdi:heart-pulse"

#==================#
#  Binary Sensors  #
#==================#
binary_sensor:


  #======================#
  #  Mi Air Purifier 3H  #
  #======================#
  - platform: template
    sensors:
      mi_air_purifier_3_3h_mode_auto:
        friendly_name: "Purifier Auto mode"
        value_template: "{{ is_state_attr('fan.mi_air_purifier_3_3h', 'preset_mode', 'Auto') and is_state('fan.mi_air_purifier_3_3h', 'on') }}"
      mi_air_purifier_3h_mode_silent:
        friendly_name: "Purifier Silent mode"
        value_template: "{{ is_state_attr('fan.mi_air_purifier_3_3h', 'preset_mode', 'Silent') and is_state('fan.mi_air_purifier_3_3h', 'on') }}"
      mi_air_purifier_3_3h_mode_favorite:
        friendly_name: "Purifier Favorite mode"
        value_template: "{{ is_state_attr('fan.mi_air_purifier_3_3h', 'preset_mode', 'Favorite') and is_state('fan.mi_air_purifier_3_3h', 'on') }}"
      mi_air_purifier_3_3h_mode_fan:
        friendly_name: "Purifier Fan mode"
        value_template: "{{ is_state_attr('fan.mi_air_purifier_3_3h', 'preset_mode', 'Fan') and is_state('fan.mi_air_purifier_3_3h', 'on') }}"
      mi_air_purifier_3_3h_mode_fan_1:
        friendly_name: "Purifier Fan mode 1"
        value_template: "{{ is_state_attr('fan.mi_air_purifier_3_3h', 'preset_mode', 'Fan') and is_state('number.mi_air_purifier_3_3h_fan_level', '1') and is_state('fan.mi_air_purifier_3_3h', 'on') }}"
      mi_air_purifier_3_3h_mode_fan_2:
        friendly_name: "Purifier Fan mode 2"
        value_template: "{{ is_state_attr('fan.mi_air_purifier_3_3h', 'preset_mode', 'Fan') and is_state('number.mi_air_purifier_3_3h_fan_level', '2') and is_state('fan.mi_air_purifier_3_3h', 'on') }}"
      mi_air_purifier_3_3h_mode_fan_3:
        friendly_name: "Purifier Fan mode 3"
        value_template: "{{ is_state_attr('fan.mi_air_purifier_3_3h', 'preset_mode', 'Fan') and is_state('number.mi_air_purifier_3_3h_fan_level', '3') and is_state('fan.mi_air_purifier_3_3h', 'on') }}"

#===============================
#===ANTISTORM===================
#===============================
binary_sensor:
  - platform: antistorm
    station_id: 136
    monitored_conditions:
      - 'storm_alarm'
      - 'rain_alarm'
      - 'storm_active'

sensor:
  - platform: antistorm
    station_id: 136
    monitored_conditions:
      - 'storm_probability'
      - 'storm_time'
      - 'rain_probability'
      - 'rain_time'
```
Regards.
